console.log("items.js loaded");

export const hats = [
	{name: "Beanie",
		id: "b1",
		price: 11,
		img: "/Assets/shopping-cart.svg",
	},
	{name: "Beanie",
		id: "b2",
		price: 12,
		img: "/Assets/shopping-cart.svg",
	},
	{name: "Beanie",
		id: "b3",
		price: 13,
		img: "/Assets/shopping-cart.svg",
	},
	{name: "Beanie",
		id: "b4",
		price: 14,
		img: "/Assets/shopping-cart.svg",
	},
	{name: "Beanie",
		id: "b5",
		price: 15,
		img: "/Assets/shopping-cart.svg",
	},
	{name: "Beanie",
		id: "b6",
		price: 16,
		img: "/Assets/shopping-cart.svg",
	}
]

export const bicycles = [
	{name: "Bicycle",
	id: "c1",
	price: 1001,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c2",
	price: 1002,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c3",
	price: 1003,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c4",
	price: 1004,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c5",
	price: 1005,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c6",
	price: 1006,
	img: "/Assets/bicycle.svg",
	},
]