
export const hats = [
	{name: "Beanie",
		id: "b1",
		price: 11,
		img: "/Assets/beanie.svg",
	},
	{name: "Beanie",
		id: "b2",
		price: 12,
		img: "/Assets/beanie.svg",
	},
	{name: "Beanie",
		id: "b3",
		price: 13,
		img: "/Assets/beanie.svg",
	},
	{name: "Beanie",
		id: "b4",
		price: 14,
		img: "/Assets/beanie.svg",
	},
	{name: "Beanie",
		id: "b5",
		price: 15,
		img: "/Assets/beanie.svg",
	},
	{name: "Beanie",
		id: "b6",
		price: 16,
		img: "/Assets/beanie.svg",
	}
]

export const bicycles = [
	{name: "Bicycle",
	id: "c1",
	price: 1001,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c2",
	price: 1002,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c3",
	price: 1003,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c4",
	price: 1004,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c5",
	price: 1005,
	img: "/Assets/bicycle.svg",
	},
	{name: "Bicycle",
	id: "c6",
	price: 1006,
	img: "/Assets/bicycle.svg",
	},
]

export const shoes = [
	{name: "Shoes",
	id: "s1",
	price: 101,
	img: "/Assets/boot.svg",
	},
	{name: "Shoes",
	id: "s2",
	price: 102,
	img: "/Assets/boot.svg",
	},
	{name: "Shoes",
	id: "s3",
	price: 103,
	img: "/Assets/boot.svg",
	},
	{name: "Shoes",
	id: "s4",
	price: 104,
	img: "/Assets/boot.svg",
	},
	{name: "Shoes",
	id: "s5",
	price: 105,
	img: "/Assets/boot.svg",
	},
	{name: "Shoes",
	id: "s6",
	price: 106,
	img: "/Assets/boot.svg",
	},
]
export const glasses = [
	{name: "Glasses",
	id: "g1",
	price: 21,
	img: "/Assets/eyeglasses.svg",
	},
	{name: "Glasses",
	id: "g2",
	price: 22,
	img: "/Assets/eyeglasses.svg",
	},
	{name: "Glasses",
	id: "g3",
	price: 23,
	img: "/Assets/eyeglasses.svg",
	},
	{name: "Glasses",
	id: "g4",
	price: 24,
	img: "/Assets/eyeglasses.svg",
	},
	{name: "Glasses",
	id: "g5",
	price: 25,
	img: "/Assets/eyeglasses.svg",
	},
	{name: "Glasses",
	id: "g6",
	price: 26,
	img: "/Assets/eyeglasses.svg",
	},
]

export const hoodies = [
	{name: "Hoody",
	id: "h1",
	price: 31,
	img: "/Assets/hoodie.svg",
	},
	{name: "Hoody",
	id: "h2",
	price: 32,
	img: "/Assets/hoodie.svg",
	},
	{name: "Hoody",
	id: "h3",
	price: 33,
	img: "/Assets/hoodie.svg",
	},
	{name: "Hoody",
	id: "h4",
	price: 34,
	img: "/Assets/hoodie.svg",
	},
	{name: "Hoody",
	id: "h5",
	price: 35,
	img: "/Assets/hoodie.svg",
	},
	{name: "Hoody",
	id: "h6",
	price: 36,
	img: "/Assets/hoodie.svg",
	},
]


export const tshirts = [
	{name: "T-Shirt",
	id: "t1",
	price: 11,
	img: "/Assets/t-shirt.svg",
	},
	{name: "T-Shirt",
	id: "t2",
	price: 12,
	img: "/Assets/t-shirt.svg",
	},
	{name: "T-Shirt",
	id: "t3",
	price: 13,
	img: "/Assets/t-shirt.svg",
	},
	{name: "T-Shirt",
	id: "t4",
	price: 14,
	img: "/Assets/t-shirt.svg",
	},
	{name: "T-Shirt",
	id: "t5",
	price: 15,
	img: "/Assets/t-shirt.svg",
	},
	{name: "T-Shirt",
	id: "t6",
	price: 16,
	img: "/Assets/t-shirt.svg",
	},

]